config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations'  }
  resources :customers, only: [:index, :show]
  get 'customer/orders/:id/size_edit', action: :size_edit, controller: 'customer/orders', as: :edit_customer_order_sizes

  devise_scope :user do
    authenticated do
      root 'customers#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :root
    end
  end

  resources :users
  namespace :customer do
    resources :orders, only: [:index, :show, :edit, :update]
    patch 'orders/size_edit/:id', to: 'orders#size_update', as: :order_sizes
  end

  authenticate :user do
    mount Resque::Server, at: '/jobs'
    mount ActionCable.server => '/cable'
  end
end

app/controllers/customers_controller.rb
require 'will_paginate/array'
class CustomersController < ApplicationController
  before_action :authenticate_user!

  def index
    @customers = Customer.search(query_params[:q]).paginate(:page => params[:page])
  end

  def show
    @customer = Customer.first
  end

  private

  def query_params
    params.permit(:q)
  end
end

app/helpers/customer_helper.rb
module CustomerHelper
  def customer_full_pull(params)
    Resque.logger = Logger.new("#{Rails.root}/log/customer_full.log", 5, 10024000)
    Resque.logger.level = Logger::INFO
    puts "Customer full_pull params recieved: #{@entity.inspect}"

    puts "Hi there getting all customers"
    puts params.inspect
    #GET /customers/count
    my_header = params['header']
    myuri = params['uri']
    puts "MYURI= #{myuri}"
    customers = HTTParty.get("https://api.rechargeapps.com/customers/count?status=active", :headers => my_header)
    num_customers = customers['count'].to_i
    Resque.logger.info "We have #{num_customers} ACTIVE customers"

    Customer.delete_all

    my_conn =  PG.connect(myuri.hostname, myuri.port, nil, nil, myuri.path[1..-1], myuri.user, myuri.password)
    puts "my_conn: #{my_conn}"
    my_insert = "insert into customers (id, shopify_customer_id, email, created_at, updated_at, status, first_name, last_name, has_card_error_in_dunning, number_subscriptions, number_active_subscriptions, first_charge_processed_at ) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) ON CONFLICT (id) DO UPDATE SET shopify_customer_id = EXCLUDED.shopify_customer_id, updated_at = EXCLUDED.updated_at, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, email = EXCLUDED.email, status = EXCLUDED.status, number_subscriptions = EXCLUDED.number_subscriptions, number_active_subscriptions = EXCLUDED.number_active_subscriptions, has_card_error_in_dunning = EXCLUDED.has_card_error_in_dunning, first_charge_processed_at = EXCLUDED.first_charge_processed_at;"
    my_conn.prepare('statement1', "#{my_insert}")

    start = Time.now
    page_size = 250
    num_pages = (num_customers/page_size.to_f).ceil
    1.upto(num_pages) do |page|
      customers = HTTParty.get("https://api.rechargeapps.com/customers?limit=250&page=#{page}&status=active", :headers => my_header)
      my_customers = customers.parsed_response['customers']
      recharge_limit = customers.response["x-recharge-limit"]
      my_customers.each do |mycust|
        puts mycust.inspect
        id = mycust['id']
        shopify_customer_id = mycust['shopify_customer_id']
        email = mycust['email']
        created_at = mycust['created_at']
        updated_at = mycust['updated_at']
        first_name = mycust['first_name']
        last_name = mycust['last_name']
        status = mycust['status']
        has_card_error_in_dunning = mycust['has_card_error_in_dunning']
        number_subscriptions = mycust['number_subscriptions']
        number_active_subscriptions = mycust['number_active_subscriptions']
        first_charge_processed_at = mycust['first_charge_processed_at']
        my_conn.exec_prepared('statement1', [id, shopify_customer_id, email, created_at, updated_at, status, first_name, last_name, has_card_error_in_dunning, number_subscriptions, number_active_subscriptions, first_charge_processed_at])
      end
      puts "Done with page #{page}/#{num_pages}"
      current = Time.now
      duration = (current - start).ceil
      puts "Running #{duration} seconds"
      determine_limits(recharge_limit, 0.65)
    end
    my_conn.close
    puts "DONE"
  end

  def customer_partial_pull(params)
    Resque.logger = Logger.new("#{Rails.root}/log/customer_partial.log", 5, 10024000)
    Resque.logger.level = Logger::INFO
    puts "Customer partial_pull params recieved: #{@entity.inspect}"

    puts "Hi there getting customers from the last 25 minutes"
    puts params.inspect
    my_header = params['header']
    myuri = params['uri']
    puts "MYURI= #{myuri}"

    twenty_five_minutes_ago_str = twenty_five_min
    Resque.logger.info "Here twenty_five_minutes_ago_str = #{twenty_five_minutes_ago_str}"
    customers_count = HTTParty.get("https://api.rechargeapps.com/customers/count?updated_at_min=\'#{twenty_five_minutes_ago_str}\'", :headers => my_header)
    my_response = customers_count
    num_customers = my_response['count'].to_i
    Resque.logger.info "We have #{num_customers} customers updated since twenty five minutes ago: #{twenty_five_minutes_ago_str}"


    my_conn =  PG.connect(myuri.hostname, myuri.port, nil, nil, myuri.path[1..-1], myuri.user, myuri.password)
    puts "my_conn: #{my_conn}"

    my_insert = "insert into customers (id, shopify_customer_id, email, created_at, updated_at, status, first_name, last_name, has_card_error_in_dunning, number_subscriptions, number_active_subscriptions, first_charge_processed_at ) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) ON CONFLICT (id) DO UPDATE SET shopify_customer_id = EXCLUDED.shopify_customer_id, updated_at = EXCLUDED.updated_at, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, email = EXCLUDED.email, status = EXCLUDED.status, number_subscriptions = EXCLUDED.number_subscriptions, number_active_subscriptions = EXCLUDED.number_active_subscriptions, has_card_error_in_dunning = EXCLUDED.has_card_error_in_dunning, first_charge_processed_at = EXCLUDED.first_charge_processed_at;"
    my_conn.prepare('statement1', "#{my_insert}")

    start = Time.now
    page_size = 250
    num_pages = (num_customers/page_size.to_f).ceil
    1.upto(num_pages) do |page|
      customers = HTTParty.get("https://api.rechargeapps.com/customers?updated_at_min=\'#{twenty_five_minutes_ago_str}\'&limit=250&page=#{page}", :headers => my_header)
      my_customers = customers.parsed_response['customers']
      recharge_limit = customers.response["x-recharge-limit"]
      my_customers.each do |mycust|
        puts mycust.inspect
        id = mycust['id']
        shopify_customer_id = mycust['shopify_customer_id']
        email = mycust['email']
        created_at = mycust['created_at']
        updated_at = mycust['updated_at']
        first_name = mycust['first_name']
        last_name = mycust['last_name']
        status = mycust['status']
        has_card_error_in_dunning = mycust['has_card_error_in_dunning']
        number_subscriptions = mycust['number_subscriptions']
        number_active_subscriptions = mycust['number_active_subscriptions']
        first_charge_processed_at = mycust['first_charge_processed_at']
        my_conn.exec_prepared('statement1', [id, shopify_customer_id, email, created_at, updated_at, status, first_name, last_name, has_card_error_in_dunning, number_subscriptions, number_active_subscriptions, first_charge_processed_at])
      end
      puts "Done with page #{page}/#{num_pages}"
      current = Time.now
      duration = (current - start).ceil
      puts "Running #{duration} seconds"
      determine_limits(recharge_limit, 0.65)
    end
    my_conn.close
    puts "DONE"
  end
end

app/helpers/order_helper.rb
module OrderHelper
  def order_full_pull(params)
    Resque.logger = Logger.new("#{Rails.root}/log/order_full.log", 5, 10024000)
    Resque.logger.level = Logger::INFO
    puts "Order full_pull params recieved: #{@entity.inspect}"

    puts "Hi there getting all orders"
    puts "params recieved: #{params}"
    my_header = params['header']
    myuri = params['uri']
    puts "MYURI= #{myuri}"
    date_range = min_max
    min = date_range['min']
    max = date_range['max']

    orders = HTTParty.get("https://api.rechargeapps.com/orders/count?scheduled_at_min=#{min}&scheduled_at_max=#{max}&status=queued", :headers => my_header)
    num_orders = orders['count'].to_i
    Resque.logger.info "We have #{num_orders} orders"

    Order.delete_all
    ActiveRecord::Base.connection.reset_pk_sequence!('order_line_items')

    my_conn =  PG.connect(myuri.hostname, myuri.port, nil, nil, myuri.path[1..-1], myuri.user, myuri.password)
    puts "my_conn: #{my_conn}"
    my_insert = "insert into orders (id, customer_id, address_id, charge_id, transaction_id, shopify_order_id, shopify_order_number,
      processed_at, status, first_name, last_name, email, payment_processor, scheduled_at,
      is_prepaid, line_items, shipping_address, total_price, billing_address, created_at, updated_at)
      values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21) ON CONFLICT (id) DO UPDATE SET shopify_order_id = EXCLUDED.shopify_order_id, shopify_order_number = EXCLUDED.shopify_order_number,
      processed_at = EXCLUDED.processed_at, status = EXCLUDED.status, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, email = EXCLUDED.email, payment_processor = EXCLUDED.payment_processor, scheduled_at = EXCLUDED.scheduled_at,
      is_prepaid = EXCLUDED.is_prepaid, total_price = EXCLUDED.total_price, line_items = EXCLUDED.line_items, shipping_address = EXCLUDED.shipping_address, billing_address = EXCLUDED.billing_address;"
    my_conn.prepare('statement1', "#{my_insert}")

    order_line_insert = "insert into order_line_items (order_id, subscription_id, grams, price,
    quantity, shopify_product_id, shopify_variant_id, properties, product_title,  sku, variant_title,
    created_at, updated_at) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13);"
    my_conn.prepare('statement2', "#{order_line_insert}")

    start = Time.now
    page_size = 250
    num_pages = (num_orders/page_size.to_f).ceil
    1.upto(num_pages) do |page|
      orders = HTTParty.get("https://api.rechargeapps.com/orders?limit=250&page=#{page}&scheduled_at_min=#{min}&scheduled_at_max=#{max}&status=queued", :headers => my_header)
      my_orders = orders.parsed_response['orders']
      recharge_limit = orders.response["x-recharge-limit"]

      my_orders.each do |my_order|
        puts my_order.inspect
        id = my_order['id']
        customer_id = my_order['customer_id']
        address_id = my_order['address_id']
        charge_id = my_order['charge_id']
        transaction_id = my_order['transaction_id']
        shopify_order_id = my_order['shopify_order_id']
        shopify_order_number = my_order['shopify_order_number']
        processed_at = my_order['processed_at']
        status = my_order['status']
        first_name = my_order['first_name']
        last_name = my_order['last_name']
        email = my_order['email']
        payment_processor = my_order['payment_processor']
        scheduled_at = my_order['scheduled_at']
        is_prepaid = my_order['is_prepaid']
        shipping_address = my_order['shipping_address'].to_json
        total_price = my_order['total_price']
        billing_address = my_order['billing_address'].to_json
        created_at = my_order['created_at']
        updated_at = my_order['updated_at']
        line_items = my_order['line_items'].to_json

        raw_line_items = my_order['line_items'][0]
        subscription_id = raw_line_items['subscription_id'].to_i
        grams = raw_line_items['grams'].to_i
        price = raw_line_items['price']
        quantity = raw_line_items['quantity']
        properties = raw_line_items['properties'].to_json
        product_title = raw_line_items['product_title']
        shopify_product_id = raw_line_items['shopify_product_id'].to_i
        shopify_variant_id = raw_line_items['shopify_variant_id'].to_i
        sku = raw_line_items['sku']
        variant_title = raw_line_items['variant_title']

        my_delete = "delete from order_line_items where order_id = \'#{id}\'"
        my_conn.exec(my_delete)
        my_conn.exec_prepared(
          'statement1', [id, customer_id, address_id, charge_id, transaction_id,
          shopify_order_id, shopify_order_number, processed_at, status, first_name, last_name, email,
          payment_processor, scheduled_at, is_prepaid, line_items, shipping_address, total_price,
          billing_address, created_at, updated_at]
        )

        my_conn.exec_prepared(
          'statement2', [id, subscription_id, grams, price, quantity, shopify_product_id,
            shopify_variant_id, properties, product_title, sku, variant_title, created_at, updated_at]
          )
      end
      puts "Done with page #{page}/#{num_pages}"
      current = Time.now
      duration = (current - start).ceil
      puts "Running #{duration} seconds"
      determine_limits(recharge_limit, 0.65)
    end
    my_conn.close
    puts "DONE"
  end

  def order_partial_pull(params)
    Resque.logger = Logger.new("#{Rails.root}/log/order_partial.log", 5, 10024000)
    Resque.logger.level = Logger::INFO
    puts "Order partial_pull params recieved: #{@entity.inspect}"
    puts "Hi there getting all orders"
    puts "params recieved: #{params}"
    my_header = params['header']
    myuri = params['uri']
    puts "MYURI= #{myuri}"

    twenty_five_minutes_ago_str = twenty_five_min
    Resque.logger.info "Here twenty_five_minutes_ago_str = #{twenty_five_minutes_ago_str}"
    orders_count = HTTParty.get("https://api.rechargeapps.com/orders/count?updated_at_min=\'#{twenty_five_minutes_ago_str}\'&status=queued", :headers => my_header)
    my_response = orders_count
    num_orders = my_response['count'].to_i
    Resque.logger.info "We have #{num_orders} orders updated since twenty five minutes ago: #{twenty_five_minutes_ago_str}"

    my_conn =  PG.connect(myuri.hostname, myuri.port, nil, nil, myuri.path[1..-1], myuri.user, myuri.password)
    puts "my_conn: #{my_conn}"
    my_insert = "insert into orders (id, customer_id, address_id, charge_id, transaction_id, shopify_order_id, shopify_order_number,
      processed_at, status, first_name, last_name, email, payment_processor, scheduled_at,
      is_prepaid, line_items, shipping_address, total_price, billing_address, created_at, updated_at)
      values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21) ON CONFLICT (id) DO UPDATE SET shopify_order_id = EXCLUDED.shopify_order_id, shopify_order_number = EXCLUDED.shopify_order_number,
      processed_at = EXCLUDED.processed_at, status = EXCLUDED.status, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, email = EXCLUDED.email, payment_processor = EXCLUDED.payment_processor, scheduled_at = EXCLUDED.scheduled_at,
      is_prepaid = EXCLUDED.is_prepaid, total_price = EXCLUDED.total_price, line_items = EXCLUDED.line_items, shipping_address = EXCLUDED.shipping_address, billing_address = EXCLUDED.billing_address;"
    my_conn.prepare('statement1', "#{my_insert}")

    start = Time.now
    page_size = 250
    num_pages = (num_orders/page_size.to_f).ceil
    1.upto(num_pages) do |page|
      orders = HTTParty.get("https://api.rechargeapps.com/orders?limit=250&page=#{page}&updated_at_min=\'#{twenty_five_minutes_ago_str}\'&status=queued", :headers => my_header)
      my_orders = orders.parsed_response['orders']
      recharge_limit = orders.response["x-recharge-limit"]

      my_orders.each do |my_order|
        puts my_order.inspect
        id = my_order['id']
        customer_id = my_order['customer_id']
        address_id = my_order['address_id']
        charge_id = my_order['charge_id']
        transaction_id = my_order['transaction_id']
        shopify_order_id = my_order['shopify_order_id']
        shopify_order_number = my_order['shopify_order_number']
        processed_at = my_order['processed_at']
        status = my_order['status']
        first_name = my_order['first_name']
        last_name = my_order['last_name']
        email = my_order['email']
        payment_processor = my_order['payment_processor']
        scheduled_at = my_order['scheduled_at']
        is_prepaid = my_order['is_prepaid']
        line_items = my_order['line_items'].to_json
        shipping_address = my_order['shipping_address'].to_json
        total_price = my_order['total_price']
        billing_address = my_order['billing_address'].to_json
        created_at = my_order['created_at']
        updated_at = my_order['updated_at']

        my_conn.exec_prepared(
          'statement1', [id, customer_id, address_id, charge_id, transaction_id,
          shopify_order_id, shopify_order_number, processed_at, status, first_name, last_name, email,
          payment_processor, scheduled_at, is_prepaid, line_items, shipping_address, total_price,
          billing_address, created_at, updated_at]
        )
      end
      puts "Done with page #{page}/#{num_pages}"
      current = Time.now
      duration = (current - start).ceil
      puts "Running #{duration} seconds"
      determine_limits(recharge_limit, 0.65)
    end
    my_conn.close
    puts "DONE"
  end

  def min_max
    my_yesterday = Date.today - 1
    my_yesterday_str = my_yesterday.strftime('%Y-%m-%d')
    my_four_months = Date.today >> 4
    my_four_months = my_four_months.end_of_month
    my_four_months_str = my_four_months.strftime('%Y-%m-%d')
    my_hash = { min: my_yesterday_str, max: my_four_months_str }
  end
end

app/views/customer/orders/edit.html.erb
<div class="edit-line-item-properties-wrapper">
  <h1>Edit Line Item Properties</h1>
  <p>For switching collections, please only update the "product_collection" field.</p>

  <%= form_for @order, as: :properties, url: customer_order_path(@order), method: :patch do |f| %>
    <table class="table">
      <tbody>
        <% @order.line_items[0]['properties'].each do |pair| %>
          <% if pair['name'] == 'product_collection' %>
            <tr>
              <td>
                <%= f.text_field pair['name'], value: pair['name'], class: "form-control", readonly: true %>
              </td>
              <td>
                <%= f.text_field pair['name'], value: pair['value'], class: "form-control", autofocus: true %>                
              </td>
            </tr>
          <% end %>
        <% end %>
        <% @order.line_items[0]['properties'].each do |pair| %>
          <% if pair['name'] == 'leggings' || pair['name'] == 'sports-bra' || pair['name'] == 'tops' || pair['name'] == 'gloves' || pair['name'] == 'sports-jacket' %>
            <tr style="display: none;">
              <td>
                <%= f.text_field pair['name'], value: pair['name'], class: "form-control" %>
              </td>
              <td>
                <%= f.text_field pair['name'], value: pair['value'], class: "form-control" %>
              </td>
            </tr>
          <% elsif pair['name'] == 'product_collection' %>
          <% else %>
            <tr>
              <td>
                <%= f.text_field pair['name'], value: pair['name'], class: "form-control", readonly: true %>
              </td>
              <td>
                <%= f.text_field pair['name'], value: pair['value'], class: "form-control", readonly: true  %>
              </td>
            </tr>
          <% end %>
        <% end %>

        <% @order.line_items[0].each do |key, value| %>
          <% if key != 'properties' %>
            <tr style="display:none;">
              <td>
                <input value="<%= key %>" type="hidden" name="line_items[<%= key %>]" class="form-control">
              </td>
              <td>
                <input value="<%= value %>" type="hidden" name="line_items[<%= key %>]" class="form-control">
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= f.submit 'Update', :class => 'btn btn-info', data: { confirm: 'Are you sure you want to update this Order?' } %>
  <% end %>
</div>

<div class="spacer"></div>

app/views/customer/orders/index.html.erb
<table class="table order-list-wrapper">
  <thead>
    <tr>
      <th>Order #</th>
      <th>Subscription id</th>
      <th>Date</th>
      <th>Total</th>
      <th>Transaction Status</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td>
          <%= link_to customer_order_path(order) do %>
            <%= order.id %>
          <% end %>
        </td>
        <td><%= order.line_items[0]['subscription_id'] %></td>
        <td><%= order.scheduled_at.strftime('%B %d, %Y')  %></td>
        <td><%= number_to_currency(order.total_price) %></td>
        <td><%= order.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customer/orders/show.html.erb
<table class="table order-show-wrapper">
  <thead>
    <tr>
      <th>Order #</th>
      <th>Date</th>
      <th>Total</th>
      <th>Transaction Status</th>
      <th>Line_Items</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @order.id %></td>
      <td><%= @order.scheduled_at.strftime('%B %d, %Y') %></td>
      <td><%= number_to_currency(@order.total_price) %></td>
      <td><%= @order.status %></td>
      <td>
        <% @order.line_items.each do |line_item| %>
          <% if line_item.has_key?('images') %>
            <img src="<%= @order.line_items[0]['images']['small'] %>"/>
          <% end %>
          <%= @order.line_items[0]['title'] %> <br />
          Quantity: <%= line_item['quantity'] %> <br />
            <% line_item['properties'].each do |prop| %>
              <% if prop.has_value?('leggings') %>
                Leggings: <%= prop['value'] %><br />
              <% end %>
              <% if prop.has_value?('sports-bra') %>
                Sports Bra: <%= prop['value'] %><br />
              <% end %>
              <% if prop.has_value?('tops') %>
                Tops: <%= prop['value'] %><br />
              <% end %>
              <% if prop.has_value?('product_collection') %>
                Product Collection: <%= prop['value'] %><br />
              <% end %>
            <% end %>
        <% end %>
        <%= link_to "Edit line items", edit_customer_order_path(@order) %>
        <%= link_to "Edit sizes", edit_customer_order_sizes_path(@order) %>
      </td>
    </tr>
  </tbody>
</table>

app/views/customer/orders/size_edit.html.erb
<div class="edit-sizes-form-wrapper">
  <h1>Edit Sizes</h1>
  <p>Order: <%= @order.id %></p>
  <%= form_for @order, as: :properties, url: customer_order_sizes_path(@order), method: :patch do |f| %>
    <table class="table">
      <tbody>
        <% @order.line_items[0]['properties'].each do |pair| %>
          <% if pair['name'] == 'leggings' || pair['name'] == 'sports-bra' || pair['name'] == 'tops' || pair['name'] == 'gloves' || pair['name'] == 'sports-jacket' %>
            <tr>
              <td>
                <%= f.text_field pair['name'], value: pair['name'], class: "form-control", readonly: true %>
              </td>
              <td>
                <%= select_tag(pair['name'], options_for_select([['XS', 'XS'], ['S', 'S'], ['M', 'M'], ['L', 'L'], ['XL', 'XL']], pair['value']), name: "properties[" + pair['name'] + "]"  ,class: 'form-control') %>
              </td>
            </tr>
          <% else %>
            <tr style="display: none;">
              <td>
                <%= f.text_field pair['name'], value: pair['name'], class: "form-control" %>
              </td>
              <td>
                <%= f.text_field pair['name'], value: pair['value'], class: "form-control" %>
              </td>
            </tr>
          <% end %>
        <% end %>

        <% @order.line_items[0].each do |key, value| %>
          <% if key != 'properties' %>
            <tr style="display:none;">
              <td>
                <input value="<%= key %>" type="hidden" name="line_items[<%= key %>]" class="form-control">
              </td>
              <td>
                <input value="<%= value %>" type="hidden" name="line_items[<%= key %>]" class="form-control">
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= f.submit 'Update Sizes', :class => 'btn btn-info', data: { confirm: 'Are you sure you want to update this Order?' } %>
  <% end %>
</div>