config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations'  }
  resources :customers, only: [:index, :show]
  get 'customer/orders/:id/size_edit', action: :size_edit, controller: 'customer/orders', as: :edit_customer_order_sizes

  devise_scope :user do
    authenticated do
      root 'customers#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :root
    end
  end

  resources :users
  namespace :customer do
    resources :orders, only: [:index, :show, :edit, :update]
    patch 'orders/size_edit/:id', to: 'orders#size_update', as: :order_sizes
  end

  authenticate :user do
    mount Resque::Server, at: '/jobs'
    mount ActionCable.server => '/cable'
  end
end

app/views/layouts/_alerts.html.erb
<% if notice.present? %>
  <p class="alert alert-primary"><%= flash.now[:notice] %></p>
<% end %>

<% if alert.present? %>
  <p class="alert alert-danger"><%= flash.now[:alert] %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CsPrepaidApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <!-- MAIN NAV START -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <%= link_to "ReCharge Prepaid Portal", authenticated_root_path, class: 'navbar-brand' %>
        <ul class="nav">
          <% if current_user.try(:admin?) %>
            <li class="nav-item px-2">
              <%= link_to 'Add new user', new_user_registration_path %>
            </li>
            <br />
          <% end %>
          <li class="nav-item px-2">
            <%= link_to 'Edit', edit_user_registration_path %>
          </li>
          <li class="nav-item px-2">
            <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      </nav>
      <div id="notifications"></div>
    <% end %>
    <!-- MAIN NAV END -->
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>